### ISSUE TITLE
一些建议：关拼写检查？（部分英文下会有下滑波浪线），加上分割线功能，选项加上注释。

### ISSUE THREAD

**Issue by cpp-jiang** [xkloveme/utools-note#2]

**Comment by 86jiang** [comment]
emmm，好像也不会自动保存

**Comment by xkloveme** [comment]
> emmm，好像也不会自动保存，保存没有快捷键

已经知晓，感谢你的建议，正在考虑下版本优化

**Comment by 86jiang** [comment]
> > emmm，好像也不会自动保存，保存没有快捷键
> 
> 已经知晓，感谢你的建议，正在考虑下版本优化
hhh感谢感谢，感觉没啥人反馈呢，昨天存了两个不同笔记，今天电脑重启，突然变成了两个一样的

**Comment by xkloveme** [comment]
优化了一版,下次添加快捷键
