### ISSUE TITLE
笔记保存后丢失

### ISSUE THREAD

**Issue by wanshaohau** [xkloveme/utools-note#3]
新入坑utools发现了note感觉发现了一个宝藏，立即使用起来，结果昨天保存两页笔记和今天刚写没多长时间的随笔保存后再打开就没了，显示不出来，也找不到。希望能够解决。系统win10专业版1909.

**Comment by xkloveme** [comment]
> 新入坑utools发现了note感觉发现了一个宝藏，立即使用起来，结果昨天保存两页笔记和今天刚写没多长时间的随笔保存后再打开就没了，显示不出来，也找不到。希望能够解决。系统win10专业版1909.

可以说下具体的操作么?我这边测试是可以的,您是不是没有点上面的保存,下个版本添加快捷键保存

**Comment by toptopdj** [comment]
保存不方便，希望添加自动保存功能，如果忘记保存那简直是灾难性的

**Comment by xkloveme** [comment]
0.0.8版本已添加自动保存
