### ISSUE TITLE
左侧的列表显示

### ISSUE THREAD

**Issue by 641031** [xkloveme/utools-note#7]
能否优化为，默认以正文的第一行为标题，在左侧显示

目前的效果看起来是抓取了全部的文字在左侧一行显示，比较凌乱

大佬辛苦了，note 看起来还是挺棒的

**Comment by xkloveme** [comment]
> 能否优化为，默认以正文的第一行为标题，在左侧显示
> 
> 目前的效果看起来是抓取了全部的文字在左侧一行显示，比较凌乱
> 
> 大佬辛苦了，note 看起来还是挺棒的

已经优化一版,添加了头部标题支持md
